language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
env:
  global:
    - secure: WkH2FDT/YPSyTp5AtkIS5P6keTeyTJmaFMsmnOx+x7G81FxZHB6hczWz7PG0D1Jt1JmKwtVgkDT1u8vBBk5JrZWqMv835iYWvtX2LRXAlWHUfA1KSf3fskIfIXsjH3rAN8LxANvYMCl8TgdoeSSHCJ7LF08cqdUym9gTBPFG4SRQCSxhsza9LGay4/d/W+vUVxa4yB7XhnTjthMXBYE6nXWwSzZnSKAK4yzBLxcGYQa5O0DukcW5ocQLHdsgqxegzHU47SG+P1VqVo5EuiyhT4iZVXC8Z9fodAn95R9Xl8xV3+x1elYELbvz1HtuBjb2q1Ud9ohcB1UViG+esRNcUFFssXsI0GlXyx2ndvyP+MuHM9kXD48Lkyrg52W4m/VGvcByDiFpLhIs/gSHXe6JR3flOBlr2iXs7rEm3VFZlawX1gbq3HP8Fc7U/ryKcylhxBxcukFmh0m5d1wUjhyB4YPiO0cYYtkJFe+Ur278XBud0Ee9qBa/3H25daTgFD9JbQANwM0JPOg4jKjoEUxOs/538VnxW/qrqatKjfuU1GZ7+4Gj4M91H9k7qVhrIg7jkvqLbRKJwoKUS6yOvgGWkhNUYOobn8azfPk8GmJPGumZm9HGN04bn7uvZJtSD9XRkgjrtWja57PEATaj8J1QoHZcrFRtsxD7eDZk9qmWqHs=
